- name: Run Backend API
  docker_container:
    name: "{{ API_CONTAINER }}" 
    image: remitranvanba/simple-api-student:latest
    networks:
      - name: "{{ NETWORK }}" 
    env:
      URL: "{{ POSTGRES_CONTAINER }}:5432"
      POSTGRES_DB: "{{ POSTGRES_DB }}" 
      POSTGRES_USER: "{{ POSTGRES_USER }}" 
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
    recreate: true
    pull: true
  vars:
    ansible_python_interpreter: /usr/bin/python3